//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csg.Data {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csg.Data.ErrorMessage", typeof(ErrorMessage).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value for &apos;{0}&apos; cannot be empty or null..
        /// </summary>
        public static string GenericValueCannotBeEmptyOrNull {
            get {
                return ResourceManager.GetString("GenericValueCannotBeEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The OrderBy expression contains an invalid property name..
        /// </summary>
        public static string InvalidOrderByExpression {
            get {
                return ResourceManager.GetString("InvalidOrderByExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified value is not in a valid format for a data column name..
        /// </summary>
        public static string SqlDbColumn_InvalidNameFormat {
            get {
                return ResourceManager.GetString("SqlDbColumn_InvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The values collection for a SqlListFilter on data field &apos;{0}&apos; is empty or null..
        /// </summary>
        public static string SqlListFilter_CollectionIsEmpty {
            get {
                return ResourceManager.GetString("SqlListFilter_CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The operation was cancelled by a child filter..
        /// </summary>
        public static string SqlSelectBuilder_OperationCancelled {
            get {
                return ResourceManager.GetString("SqlSelectBuilder_OperationCancelled", resourceCulture);
            }
        }
    }
}
